// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.Bank;
import com.exc.exchangecurrency.domain.exc.BankDataOnDemand;
import com.exc.exchangecurrency.domain.exc.BankIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BankIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BankIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BankIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BankIntegrationTest: @Transactional;
    
    @Autowired
    BankDataOnDemand BankIntegrationTest.dod;
    
    @Test
    public void BankIntegrationTest.testCountBanks() {
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", dod.getRandomBank());
        long count = Bank.countBanks();
        Assert.assertTrue("Counter for 'Bank' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BankIntegrationTest.testFindBank() {
        Bank obj = dod.getRandomBank();
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bank' failed to provide an identifier", id);
        obj = Bank.findBank(id);
        Assert.assertNotNull("Find method for 'Bank' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bank' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BankIntegrationTest.testFindAllBanks() {
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", dod.getRandomBank());
        long count = Bank.countBanks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bank', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bank> result = Bank.findAllBanks();
        Assert.assertNotNull("Find all method for 'Bank' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bank' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BankIntegrationTest.testFindBankEntries() {
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", dod.getRandomBank());
        long count = Bank.countBanks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bank> result = Bank.findBankEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bank' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bank' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BankIntegrationTest.testFlush() {
        Bank obj = dod.getRandomBank();
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bank' failed to provide an identifier", id);
        obj = Bank.findBank(id);
        Assert.assertNotNull("Find method for 'Bank' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBank(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bank' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BankIntegrationTest.testMergeUpdate() {
        Bank obj = dod.getRandomBank();
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bank' failed to provide an identifier", id);
        obj = Bank.findBank(id);
        boolean modified =  dod.modifyBank(obj);
        Integer currentVersion = obj.getVersion();
        Bank merged = (Bank)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bank' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BankIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", dod.getRandomBank());
        Bank obj = dod.getNewTransientBank(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bank' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bank' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Bank' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BankIntegrationTest.testRemove() {
        Bank obj = dod.getRandomBank();
        Assert.assertNotNull("Data on demand for 'Bank' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bank' failed to provide an identifier", id);
        obj = Bank.findBank(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bank' with identifier '" + id + "'", Bank.findBank(id));
    }
    
}
