// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.Currency;
import com.exc.exchangecurrency.domain.exc.CurrencyDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CurrencyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CurrencyDataOnDemand: @Component;
    
    private Random CurrencyDataOnDemand.rnd = new SecureRandom();
    
    private List<Currency> CurrencyDataOnDemand.data;
    
    public Currency CurrencyDataOnDemand.getNewTransientCurrency(int index) {
        Currency obj = new Currency();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setCurrency_Name(obj, index);
        setStatus(obj, index);
        setSymbol(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void CurrencyDataOnDemand.setCreatedBy(Currency obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void CurrencyDataOnDemand.setCreatedDate(Currency obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void CurrencyDataOnDemand.setCurrency_Name(Currency obj, int index) {
        String currency_Name = "currency_Name_" + index;
        obj.setCurrency_Name(currency_Name);
    }
    
    public void CurrencyDataOnDemand.setStatus(Currency obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void CurrencyDataOnDemand.setSymbol(Currency obj, int index) {
        String symbol = "symbol_" + index;
        obj.setSymbol(symbol);
    }
    
    public void CurrencyDataOnDemand.setUpdatedBy(Currency obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void CurrencyDataOnDemand.setUpdatedDate(Currency obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public Currency CurrencyDataOnDemand.getSpecificCurrency(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Currency obj = data.get(index);
        Long id = obj.getId();
        return Currency.findCurrency(id);
    }
    
    public Currency CurrencyDataOnDemand.getRandomCurrency() {
        init();
        Currency obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Currency.findCurrency(id);
    }
    
    public boolean CurrencyDataOnDemand.modifyCurrency(Currency obj) {
        return false;
    }
    
    public void CurrencyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Currency.findCurrencyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Currency' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Currency>();
        for (int i = 0; i < 10; i++) {
            Currency obj = getNewTransientCurrency(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
