// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.Currency;
import com.exc.exchangecurrency.domain.exc.CurrencyDataOnDemand;
import com.exc.exchangecurrency.domain.exc.CurrencyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CurrencyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CurrencyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CurrencyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CurrencyIntegrationTest: @Transactional;
    
    @Autowired
    CurrencyDataOnDemand CurrencyIntegrationTest.dod;
    
    @Test
    public void CurrencyIntegrationTest.testCountCurrencys() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = Currency.countCurrencys();
        Assert.assertTrue("Counter for 'Currency' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CurrencyIntegrationTest.testFindCurrency() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = Currency.findCurrency(id);
        Assert.assertNotNull("Find method for 'Currency' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Currency' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CurrencyIntegrationTest.testFindAllCurrencys() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = Currency.countCurrencys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Currency', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Currency> result = Currency.findAllCurrencys();
        Assert.assertNotNull("Find all method for 'Currency' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Currency' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CurrencyIntegrationTest.testFindCurrencyEntries() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        long count = Currency.countCurrencys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Currency> result = Currency.findCurrencyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Currency' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Currency' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CurrencyIntegrationTest.testFlush() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = Currency.findCurrency(id);
        Assert.assertNotNull("Find method for 'Currency' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCurrency(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Currency' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurrencyIntegrationTest.testMergeUpdate() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = Currency.findCurrency(id);
        boolean modified =  dod.modifyCurrency(obj);
        Integer currentVersion = obj.getVersion();
        Currency merged = (Currency)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Currency' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CurrencyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", dod.getRandomCurrency());
        Currency obj = dod.getNewTransientCurrency(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Currency' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Currency' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CurrencyIntegrationTest.testRemove() {
        Currency obj = dod.getRandomCurrency();
        Assert.assertNotNull("Data on demand for 'Currency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Currency' failed to provide an identifier", id);
        obj = Currency.findCurrency(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Currency' with identifier '" + id + "'", Currency.findCurrency(id));
    }
    
}
