// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.DateExchangeCuurency;
import com.exc.exchangecurrency.domain.exc.DateExchangeCuurencyDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DateExchangeCuurencyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DateExchangeCuurencyDataOnDemand: @Component;
    
    private Random DateExchangeCuurencyDataOnDemand.rnd = new SecureRandom();
    
    private List<DateExchangeCuurency> DateExchangeCuurencyDataOnDemand.data;
    
    public DateExchangeCuurency DateExchangeCuurencyDataOnDemand.getNewTransientDateExchangeCuurency(int index) {
        DateExchangeCuurency obj = new DateExchangeCuurency();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setDateExchangeCuurency(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void DateExchangeCuurencyDataOnDemand.setCreatedBy(DateExchangeCuurency obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void DateExchangeCuurencyDataOnDemand.setCreatedDate(DateExchangeCuurency obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void DateExchangeCuurencyDataOnDemand.setDateExchangeCuurency(DateExchangeCuurency obj, int index) {
        Integer dateExchangeCuurency = new Integer(index);
        obj.setDateExchangeCuurency(dateExchangeCuurency);
    }
    
    public void DateExchangeCuurencyDataOnDemand.setStatus(DateExchangeCuurency obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void DateExchangeCuurencyDataOnDemand.setUpdatedBy(DateExchangeCuurency obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void DateExchangeCuurencyDataOnDemand.setUpdatedDate(DateExchangeCuurency obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public DateExchangeCuurency DateExchangeCuurencyDataOnDemand.getSpecificDateExchangeCuurency(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DateExchangeCuurency obj = data.get(index);
        Long id = obj.getId();
        return DateExchangeCuurency.findDateExchangeCuurency(id);
    }
    
    public DateExchangeCuurency DateExchangeCuurencyDataOnDemand.getRandomDateExchangeCuurency() {
        init();
        DateExchangeCuurency obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DateExchangeCuurency.findDateExchangeCuurency(id);
    }
    
    public boolean DateExchangeCuurencyDataOnDemand.modifyDateExchangeCuurency(DateExchangeCuurency obj) {
        return false;
    }
    
    public void DateExchangeCuurencyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DateExchangeCuurency.findDateExchangeCuurencyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DateExchangeCuurency' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DateExchangeCuurency>();
        for (int i = 0; i < 10; i++) {
            DateExchangeCuurency obj = getNewTransientDateExchangeCuurency(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
