// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.DateExchangeCuurency;
import com.exc.exchangecurrency.domain.exc.DateExchangeCuurencyDataOnDemand;
import com.exc.exchangecurrency.domain.exc.DateExchangeCuurencyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DateExchangeCuurencyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DateExchangeCuurencyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DateExchangeCuurencyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DateExchangeCuurencyIntegrationTest: @Transactional;
    
    @Autowired
    DateExchangeCuurencyDataOnDemand DateExchangeCuurencyIntegrationTest.dod;
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testCountDateExchangeCuurencys() {
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", dod.getRandomDateExchangeCuurency());
        long count = DateExchangeCuurency.countDateExchangeCuurencys();
        Assert.assertTrue("Counter for 'DateExchangeCuurency' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testFindDateExchangeCuurency() {
        DateExchangeCuurency obj = dod.getRandomDateExchangeCuurency();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to provide an identifier", id);
        obj = DateExchangeCuurency.findDateExchangeCuurency(id);
        Assert.assertNotNull("Find method for 'DateExchangeCuurency' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DateExchangeCuurency' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testFindAllDateExchangeCuurencys() {
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", dod.getRandomDateExchangeCuurency());
        long count = DateExchangeCuurency.countDateExchangeCuurencys();
        Assert.assertTrue("Too expensive to perform a find all test for 'DateExchangeCuurency', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DateExchangeCuurency> result = DateExchangeCuurency.findAllDateExchangeCuurencys();
        Assert.assertNotNull("Find all method for 'DateExchangeCuurency' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DateExchangeCuurency' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testFindDateExchangeCuurencyEntries() {
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", dod.getRandomDateExchangeCuurency());
        long count = DateExchangeCuurency.countDateExchangeCuurencys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DateExchangeCuurency> result = DateExchangeCuurency.findDateExchangeCuurencyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DateExchangeCuurency' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DateExchangeCuurency' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testFlush() {
        DateExchangeCuurency obj = dod.getRandomDateExchangeCuurency();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to provide an identifier", id);
        obj = DateExchangeCuurency.findDateExchangeCuurency(id);
        Assert.assertNotNull("Find method for 'DateExchangeCuurency' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDateExchangeCuurency(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DateExchangeCuurency' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testMergeUpdate() {
        DateExchangeCuurency obj = dod.getRandomDateExchangeCuurency();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to provide an identifier", id);
        obj = DateExchangeCuurency.findDateExchangeCuurency(id);
        boolean modified =  dod.modifyDateExchangeCuurency(obj);
        Integer currentVersion = obj.getVersion();
        DateExchangeCuurency merged = (DateExchangeCuurency)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DateExchangeCuurency' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", dod.getRandomDateExchangeCuurency());
        DateExchangeCuurency obj = dod.getNewTransientDateExchangeCuurency(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DateExchangeCuurency' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DateExchangeCuurency' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DateExchangeCuurencyIntegrationTest.testRemove() {
        DateExchangeCuurency obj = dod.getRandomDateExchangeCuurency();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DateExchangeCuurency' failed to provide an identifier", id);
        obj = DateExchangeCuurency.findDateExchangeCuurency(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DateExchangeCuurency' with identifier '" + id + "'", DateExchangeCuurency.findDateExchangeCuurency(id));
    }
    
}
