// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.ExchangeCurrency;
import com.exc.exchangecurrency.domain.exc.ExchangeCurrencyDataOnDemand;
import com.exc.exchangecurrency.domain.exc.ExchangeCurrencyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExchangeCurrencyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExchangeCurrencyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExchangeCurrencyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExchangeCurrencyIntegrationTest: @Transactional;
    
    @Autowired
    ExchangeCurrencyDataOnDemand ExchangeCurrencyIntegrationTest.dod;
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testCountExchangeCurrencys() {
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", dod.getRandomExchangeCurrency());
        long count = ExchangeCurrency.countExchangeCurrencys();
        Assert.assertTrue("Counter for 'ExchangeCurrency' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testFindExchangeCurrency() {
        ExchangeCurrency obj = dod.getRandomExchangeCurrency();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to provide an identifier", id);
        obj = ExchangeCurrency.findExchangeCurrency(id);
        Assert.assertNotNull("Find method for 'ExchangeCurrency' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExchangeCurrency' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testFindAllExchangeCurrencys() {
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", dod.getRandomExchangeCurrency());
        long count = ExchangeCurrency.countExchangeCurrencys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExchangeCurrency', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExchangeCurrency> result = ExchangeCurrency.findAllExchangeCurrencys();
        Assert.assertNotNull("Find all method for 'ExchangeCurrency' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExchangeCurrency' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testFindExchangeCurrencyEntries() {
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", dod.getRandomExchangeCurrency());
        long count = ExchangeCurrency.countExchangeCurrencys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExchangeCurrency> result = ExchangeCurrency.findExchangeCurrencyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ExchangeCurrency' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExchangeCurrency' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testFlush() {
        ExchangeCurrency obj = dod.getRandomExchangeCurrency();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to provide an identifier", id);
        obj = ExchangeCurrency.findExchangeCurrency(id);
        Assert.assertNotNull("Find method for 'ExchangeCurrency' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExchangeCurrency(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ExchangeCurrency' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testMergeUpdate() {
        ExchangeCurrency obj = dod.getRandomExchangeCurrency();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to provide an identifier", id);
        obj = ExchangeCurrency.findExchangeCurrency(id);
        boolean modified =  dod.modifyExchangeCurrency(obj);
        Integer currentVersion = obj.getVersion();
        ExchangeCurrency merged = (ExchangeCurrency)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ExchangeCurrency' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", dod.getRandomExchangeCurrency());
        ExchangeCurrency obj = dod.getNewTransientExchangeCurrency(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExchangeCurrency' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ExchangeCurrency' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExchangeCurrencyIntegrationTest.testRemove() {
        ExchangeCurrency obj = dod.getRandomExchangeCurrency();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExchangeCurrency' failed to provide an identifier", id);
        obj = ExchangeCurrency.findExchangeCurrency(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ExchangeCurrency' with identifier '" + id + "'", ExchangeCurrency.findExchangeCurrency(id));
    }
    
}
