// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain.exc;

import com.exc.exchangecurrency.domain.exc.DateExchangeCuurency;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DateExchangeCuurency_Roo_Configurable {
    
    declare @type: DateExchangeCuurency: @Configurable;
    
}
