// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.exchangecurrency.domain;

import com.exc.exchangecurrency.domain.EMailTemplate;
import com.exc.exchangecurrency.domain.EMailTemplateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EMailTemplateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EMailTemplateDataOnDemand: @Component;
    
    private Random EMailTemplateDataOnDemand.rnd = new SecureRandom();
    
    private List<EMailTemplate> EMailTemplateDataOnDemand.data;
    
    public EMailTemplate EMailTemplateDataOnDemand.getNewTransientEMailTemplate(int index) {
        EMailTemplate obj = new EMailTemplate();
        setCode(obj, index);
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setEmailTemplate(obj, index);
        setStatus(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void EMailTemplateDataOnDemand.setCode(EMailTemplate obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void EMailTemplateDataOnDemand.setCreatedBy(EMailTemplate obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void EMailTemplateDataOnDemand.setCreatedDate(EMailTemplate obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void EMailTemplateDataOnDemand.setEmailTemplate(EMailTemplate obj, int index) {
        String emailTemplate = "foo" + index + "@bar.com";
        obj.setEmailTemplate(emailTemplate);
    }
    
    public void EMailTemplateDataOnDemand.setStatus(EMailTemplate obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void EMailTemplateDataOnDemand.setUpdatedBy(EMailTemplate obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void EMailTemplateDataOnDemand.setUpdatedDate(EMailTemplate obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public EMailTemplate EMailTemplateDataOnDemand.getSpecificEMailTemplate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EMailTemplate obj = data.get(index);
        Long id = obj.getId();
        return EMailTemplate.findEMailTemplate(id);
    }
    
    public EMailTemplate EMailTemplateDataOnDemand.getRandomEMailTemplate() {
        init();
        EMailTemplate obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EMailTemplate.findEMailTemplate(id);
    }
    
    public boolean EMailTemplateDataOnDemand.modifyEMailTemplate(EMailTemplate obj) {
        return false;
    }
    
    public void EMailTemplateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EMailTemplate.findEMailTemplateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EMailTemplate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EMailTemplate>();
        for (int i = 0; i < 10; i++) {
            EMailTemplate obj = getNewTransientEMailTemplate(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
